export type RegistroSello = {
  id: number | string;
  codigo?: string;
  obra?: string;
  fecha?: string;
  estado?: string;
  obraId?: string;
  usuarioId?: string;
  diaSemana?: string;
  descripcionMaterial?: string;
  accesibilidad?: number;
  obraNombre?: string;
  usuarioNombre?: string;
  codigoBeck?: string;
  itemizadoMandanteId?: string;
  itemizadoMandanteNombre?: string;
  itemizadoBeck: string;
  itemizadoSacyr: string;
  fechaEjecucion: string; // ISO
  dia: string;
  piso: string;
  ejeAlfabetico: string;
  ejeNumerico: string;
  nombreSellador: string;
  fotoUrl?: string;
  fotosUrls?: string[];
  recinto: string;
  numeroSello: string;
  cantidadSellos: number;
  holguraCm: number;
  factorHolgura: 1 | 1.2 | 1.4 | 1.8;
  cieloModular: 1 | 2 | 3;
  cantidadSellosConFactor: number;
  factorPorHolguras?: number | string | null;
  cantidadSellosConFactores?: number | string | null;
  aislacion?: number | string | null;
  cantidadSellosAislacion?: number | string | null;
  reparacionTabique?: number | string | null;
  cantidadFinal?: number | string | null;
  observaciones?: string;
  tipoRegistro?: string;
  metrosLineales?: number;
  motivoRechazo?: string | null;
  fechaRechazo?: string | null;
  rechazadoPor?: { id?: string; nombre: string } | null;
  esCorreccion?: boolean;
  registroOrigenId?: string | null;
  registroOrigen?: { id?: string; motivoRechazo?: string | null } | null;
  rendimientoSellosEsperadoDiario?: number | null;
  rendimientoReparacionEsperadoDiario?: number | null;
  cantidadEjecutada?: number | null;
  rendimientoIndividual?: number | null;
  rendimientoIndividualPct?: number | null;
  validadoCliente?: boolean | null;
  pdfFirmadoUrl?: string | null;
  seleccionadoParaInspeccion?: boolean | null;
  inspeccionEstado?: "no_enviado" | "en_inspeccion" | "inspeccionado";
  fechaSeleccionInspeccion?: string | null;
  seleccionadoInspeccionPorId?: string | null;
  seleccionadoInspeccionPor?: { id?: string | null; nombre?: string | null } | null;
  controlesInspeccion?: Array<{
    id?: string | null;
    conformidad?: string | null;
    fecha?: string | null;
    createdAt?: string | null;
  }>;
};
